### ISSUE TITLE
Adicionar alterações da branch Dev na V2 do Mural

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/mural#368]
Algumas alterações que foram realizadas na `dev` mais recentemente não foram feitas na `v2` do mural. Essa é uma lista das alterações realizadas que ainda não estão na `v2` e algumas sugestões/bugs para serem ajustadas.

- [x] Data de entrega mínima: Na dev tem um limite de tempo pra sugestão de data de entrega de serviço (foi utilizado 10 dias lá) | Tarefa: #376
---
- [x] Envio de E-mail ao criar uma solicitação, alteração de estado da solicitação, comentário na solicitação, etc. | [Referência](https://github.com/practice-uffs/mural/pull/308)  | Tarefa #375
---
- [ ] Envio de notificação com o FireBase ao modificar estado da solicitação e comentário | Tarefa #374
---
- [x] Bug no menu | Tarefa #372 
- [x] Bug na aba de [/gerenciar/servicos/servicos ](https://practice.uffs.edu.br/mural/gerenciar/servicos) | Tarefa #373 
- [x] Bug na aba [/gerenciar/servicos/pedidos](https://practice.uffs.edu.br/mural/gerenciar/pedidos) | Tarefa #371
---
- [x]  Quando deslogado, ao clicar em solicitar serviço, você é direcionado para fazer login. Mas ao fazer login você vai para a página inicial, não para o [formulário de serviços](https://v2.mural.practice.uffs.cc/servicos/solicitar/1) ou a área de [solicitar serviços](https://v2.mural.practice.uffs.cc/servicos) | Tarefa #370
---
- [x] Para o aplicativo: aumentar tempo que token para login expira no servidor. | Tarefa #369
---
- [x]  Melhorias na responsividade do mural para smartphones | Tarefa #366 
- [x] Subnavbar na aba de solicitar serviços (para não ter rolagem tão grande) | Tarefa #366

_Originally posted by @alissonpeloso in https://github.com/practice-uffs/mural/issues/367#issuecomment-906422120_
